### ISSUE TITLE
watchbot app crashes when accel

### ISSUE THREAD

**Issue by shirou** [hybridgroup/watchbot#22]
At least in my pebble black (version 2.2.2), after open the Accelerometer window, the app will be crashed very soon.

I found this is caused by samples value of Accel.config,
```
Accel.config({rate: 10, samples: 1});
```

1 was too low. I set 5 and works with many errors. I think it should be much bigger to safety.

Thank you.

**Comment by deadprogram** [comment]
Hi, @shirou 

This issue should be corrected in the new release. Can you please verify? Thanks!

**Comment by shirou** [comment]
I'm very sorry. I have not noticed your reply. And I can not verify because now I have Pebble time and give previous Pebble to my friend.
However, this commit seems works fine. Thank you so much!
